DECLARE @QTDEPRODUTOS INT;
SELECT @QTDEPRODUTOS = MAX(produtoid) FROM produto;
PRINT @QTDEPRODUTOS;

DECLARE @TXTQTDE VARCHAR(255);
SELECT @TXTQTDE = CAST(@QTDEPRODUTOS AS VARCHAR(255));

DECLARE @MENSAGEM VARCHAR(255);
SET @MENSAGEM = 'Quantidade de Produtos Cadastrados = '+ @TXTQTDE;
PRINT @MENSAGEM;

DECLARE @QTDECHAR INT ;
SELECT @QTDECHAR = LEN(@MENSAGEM);

PRINT 'Qtde de Caracteres = '+ CAST(@QTDECHAR AS VARCHAR(255));